version: "3.8"

services:
  postgres:
    container_name: script_bot_db
    image: postgres:latest
    environment:
      POSTGRES_DB: script_bot_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - script_bot_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d script_bot_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: script_bot_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - script_bot_network
    depends_on:
      - postgres

networks:
  script_bot_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
